site_name: Chiefeh Blog
site_description: 'Somewhere to post my stuff'
site_author: 'Gregory Bennett'
docs_dir: docs/
repo_name: 'chiefeh/chiefeh.github.io'
repo_url: 'https://github.com/chiefeh/chiefeh.github.io'
nav:
    - Home: index.md
    - About: about.md
    - Git: git.md
    - Markdown: markdown.md
    - IaC: infra-as-code.md
theme:
  name: material
#  palette:
#    scheme: slate
#    primary: light blue
#    accent: deep purple
  palette:
    - scheme: default
      toggle:
          icon: material/toggle-switch
          name: Switch to light mode
    - scheme: slate
      toggle:
          icon: material/toggle-switch-off-outline
          name: Switch to dark mode
