name: 'podman'
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material
      - run: |
        sed -i 's/github.chiefeh.io/container $GITHUB_REF/g' docs/index.md
      - run: mkdocs build
      - run: podman build -t my-first-container -f Containerfile
      - run: podman login -u="chiefeh" -p="$QUAY_PASSWORD" quay.io
      - run: podman push my-first-container quay.io/chiefeh/my-first-container
